---
apiVersion: v1
kind: Template
metadata:
  name: platform-changelog
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: platform-changelog
  spec:
    envName: ${ENV_NAME}
    testing:
      iqePlugin: platform-changelog
    database:
      name: platformchangelog
    deployments:
    - name: api
      webServices:
        public:
          enabled: True
      minReplicas: ${{API_REPLICAS}}
      podSpec:
        initContainers:
          - command:
            - ./platform-changelog-migration
            image: ${IMAGE}:${IMAGE_TAG}
            inheritEnv: True
        minReadySeconds: 15
        progressDeadlineSeconds: 600
        image: ${IMAGE}:${IMAGE_TAG}
        command:
          - ./platform-changelog-api
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: ${API_CPU_LIMIT}
            memory: ${API_MEMORY_LIMIT}
          requests:
            cpu: ${API_CPU_REQUEST}
            memory: ${API_MEMORY_REQUEST}
        env:
          - name: HOST
            value: ${HOST}
          - name: LOGLEVEL
            value: ${LOGLEVEL}
          - name: DB_IMPL
            value: ${DB_IMPL}
          - name: SKIP_WEBHOOK_VALIDATION
            value: ${SKIP_WEBHOOK_VALIDATION}
          - name: GITHUB_WEBHOOK_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                key: github-secret-token
                name: github-secret-token
          - name: GITLAB_WEBHOOK_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                key: gitlab-secret-token
                name: gitlab-secret-token
    jobs:
    - name: vacuum
      schedule: '@daily'
      suspend: ${{CLEANER_SUSPEND}}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command:
          - ./tools/cron-job.sh
        resources:
          limits:
            cpu: ${API_CPU_LIMIT}
            memory: ${API_MEMORY_LIMIT}
          requests:
            cpu: 200m
            memory: 256Mi

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: platform-changelog
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.prometheus: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"platform-changelog"}}'
- apiVersion: v1
  kind: Service
  metadata:
    name: platform-changelog-oauth-proxy
  spec:
    clusterIP: None
    ports:
    - name: http
      port: 4180
      protocol: TCP
    selector:
      app: platform-changelog
      pod: platform-changelog-oauth-proxy
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: platform-changelog
    name: platform-changelog-oauth-proxy
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: "oauth-proxy does not need 3 replicas"
  spec:
    replicas: ${{PROXY_REPLICAS}}
    selector:
      matchLabels:
        app: platform-changelog
    template:
      metadata:
        labels:
          app: platform-changelog
          pod: platform-changelog-oauth-proxy
      spec:
        serviceAccountName: platform-changelog
        containers:
        - name: oauth-proxy
          image: ${OAUTH_PROXY_IMAGE_NAME}:${OAUTH_PROXY_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 4180
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /oauth/healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /oauth/healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          resources:
            limits:
              cpu: ${API_CPU_LIMIT}
              memory: ${API_MEMORY_LIMIT}
            requests:
              cpu: 200m
              memory: 256Mi
          args:
          - --http-address=:4180
          - --https-address=
          - --provider=openshift
          - --openshift-service-account=platform-changelog
          - --upstream=http://localhost:9000
          - --cookie-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token

- apiVersion: v1
  kind: Secret
  metadata:
    name: github-secret-token
    labels:
      app: platform-changelog
  data:
    github-secret-token: NDkzODRhZWM3ZDNmMGU3NzFlNTljYmFiY2U4MzY2ZjI4ZWFjYWU2NA==
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    name: gitlab-secret-token
    labels:
      app: platform-changelog
  data:
    gitlab-secret-token: MzExYmRjYTdjZWNhNmNkODMyYWUxYzFhNjU0ZDFhM2M0ZGEwZWJkMw==
  type: Opaque

parameters:
- description: Initial amount of memory the platform-changlog container will request.
  displayName: Memory Request
  name: API_MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory for the platform-changlog.
  displayName: Memory Limit
  name: API_MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Initial amount of cpu the platform-changlog will request.
  displayName: CPU Request
  name: API_CPU_REQUEST
  required: true
  value: 200m
- description: Maximum amount of cpu the platform-changlog can use.
  displayName: CPU Limit
  name: API_CPU_LIMIT
  required: true
  value: 500m
- description: The log level to use for logging
  displayName: The log level to use for logging
  name: LOGLEVEL
  required: true
  value: DEBUG
- description: The number of replicas to use for the platform-changlog
  name: API_REPLICAS
  value: '3'
- description: Image
  name: IMAGE
  required: true
  value: quay.io/cloudservices/platform-changelog-go
- description: Image tag
  name: IMAGE_TAG
  required: true
- name: ENV_NAME
  value: platform-changelog-go
  required: true
- name: CLEANER_SUSPEND
  value: 'true'
- name: DB_IMPL
  value: 'impl'
- name: SKIP_WEBHOOK_VALIDATION
  value: 'false'
- name: PROXY_REPLICAS
  value: '1'
- name: OAUTH_PROXY_IMAGE_NAME
  value: quay.io/openshift/origin-oauth-proxy
- name: OAUTH_PROXY_IMAGE_TAG
  value: "4.10.0"
