services:
  rbac:
    display_name: RBAC
    tenant: Insights
    gh_repo: https://github.com/RedHatInsights/insights-rbac
    branch: master
    namespace: rbac-prod
  entitlements:
    display_name: Entitlements
    tenant: Insights
    gh_repo: https://github.com/RedHatInsights/entitlements-api-go
    branch: master
    namespace: entitlements-prod
  ingress:
    display_name: Ingress
    tenant: Insights
    gh_repo: https://github.com/RedHatInsights/insights-ingress-go
    branch: master
    namespace: ingress-prod
  insights-engine:
    display_name: Insights Engine
    tenant: Insights
    gl_repo: https://gitlab.cee.redhat.com/insights-platform/insights-engine
    branch: master 
    namespace: engine-prod
