services:
  platform-changelog:
    display_name: Platform Changelog
    tenant: Insights
  rbac:
    display_name: RBAC
    tenant: Insights
  entitlements:
    display_name: Entitlements
    tenant: Insights
  ingress:
    display_name: Ingress
    tenant: Insights
  insights-engine:
    display_name: Insights Engine
    tenant: Insights
  cloud-connector:
    display_name: Cloud Connector
    tenant: Insights
  export-service:
    display_name: Export Service
    tenant: Insights
  3scale:
    display_name: 3scale
    tenant: Insights
  playbook-dispatcher:
    display_name: Playbook Dispatcher
    tenant: Insights
  notifications:
    display_name: Notifications
    tenant: Insights
  xjoin:
    display_name: xjoin api gateway
    tenant: Insights
  host-inventory:
    display_name: Host Inventory
    tenant: Insights
  host-inventory-frontend:
    display_name: Host Inventory Frontend
    tenant: Insights
  advisor:
    display_name: Advisor
    tenant: Insights
  edge:
    display_name: Edge
    tenant: Insights
  chrome-service:
    display_name: Chrome Service
    tenant: Insights
  chrome-service-backend:
    display_name: Chrome Service Backend
    tenant: Insights
  hac:
    display_name: HAC
    tenant: Insights
  content-sources:
    display_name: Content Sources
    tenant: Insights
